services:
  backend:
    image: prompt-store:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompt-store
    ports:
      - "8989:8989"
    volumes:
      - .:/app
    networks:
      - app-network
    environment:
      - ENV=development
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge